# Generated by Django 3.2.7 on 2021-11-02 04:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='CS3240', max_length=100)),
                ('enrollment', models.IntegerField(default=50)),
                ('notes', models.FileField(blank=True, null=True, upload_to='')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['class_name'],
            },
        ),
    ]
