# Generated by Django 3.2.7 on 2021-11-02 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_auto_20211102_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_set', to='organizer.class'),
        ),
    ]
