# Generated by Django 3.2.7 on 2021-11-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_alter_notes_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='CS3240', max_length=100)),
                ('review_text', models.CharField(default='Great class!', max_length=100)),
            ],
        ),
    ]
