# Generated by Django 3.2.7 on 2021-11-08 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_alter_notes_file'),
        ('organizer', '0002_category_todolist'),
    ]

    operations = [
    ]
