# Generated by Django 3.2.7 on 2021-11-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_alter_reviews_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='class_prof',
            field=models.CharField(default='McBurnster', max_length=100),
        ),
    ]
