# Generated by Django 3.2.7 on 2021-11-08 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0006_reviews_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='course',
            new_name='c',
        ),
    ]
