# Generated by Django 3.2.7 on 2021-11-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0007_rename_course_reviews_c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='class_name',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='class_prof',
            field=models.CharField(default='Class Instructor', max_length=100),
        ),
    ]
