# Generated by Django 3.2.7 on 2021-11-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0009_rename_c_reviews_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='class_prof',
            new_name='class_Instructor',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='review_text',
            new_name='review',
        ),
    ]
