# Generated by Django 3.2.7 on 2021-11-08 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_merge_0002_alter_notes_file_0002_category_todolist'),
        ('organizer', '0010_auto_20211108_1922'),
    ]

    operations = [
    ]
