# Generated by Django 3.2.7 on 2021-11-13 17:52

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('organizer', '0014_class_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='tags',
        ),
        migrations.AddField(
            model_name='notes',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
