# Generated by Django 3.2.7 on 2021-11-16 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_auto_20211115_1440'),
        ('organizer', '0015_auto_20211113_1752'),
    ]

    operations = [
    ]
