# Generated by Django 3.1.13 on 2021-11-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0017_auto_20211118_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
