# Generated by Django 3.2.7 on 2021-11-20 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0020_auto_20211119_1907'),
        ('organizer', '0020_auto_20211119_2328'),
    ]

    operations = [
    ]
