# Generated by Django 3.2.9 on 2021-11-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0023_auto_20211123_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={},
        ),
        migrations.AddField(
            model_name='todolist',
            name='email',
            field=models.CharField(default='someone@gmail.com', max_length=250),
        ),
    ]
