# Generated by Django 3.2.7 on 2021-11-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0024_auto_20211124_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2021-11-28'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2021-11-28'),
        ),
    ]
