# Generated by Django 3.2.7 on 2021-11-30 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0024_auto_20211128_0125'),
        ('organizer', '0025_auto_20211127_2039'),
    ]

    operations = [
    ]
