# Generated by Django 3.2.7 on 2021-11-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0026_merge_0024_auto_20211128_0125_0025_auto_20211127_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2021-11-30'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2021-11-30'),
        ),
    ]
