# Generated by Django 3.2.7 on 2021-11-30 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0027_auto_20211130_1412'),
        ('organizer', '0027_auto_20211130_2041'),
    ]

    operations = [
    ]
