# Generated by Django 3.2.9 on 2021-12-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0029_auto_20211130_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='classSection',
            field=models.CharField(default='No Class', max_length=200),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2021-12-05'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2021-12-05'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
