# Generated by Django 3.2.7 on 2021-12-05 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0031_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='class_Instructor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_set', to='organizer.class'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2021-12-05'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2021-12-05'),
        ),
    ]
