# Generated by Django 3.2.9 on 2021-12-05 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0030_auto_20211204_1925'),
        ('organizer', '0031_event_user'),
    ]

    operations = [
    ]
