# Generated by Django 3.2.9 on 2021-12-05 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0032_merge_0030_auto_20211204_1925_0031_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='classSection',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_set', to='organizer.class'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
